device: 0
save_dir : 'log'

data:
  train_file: 'data/ptb-train.pickle'
  val_file: 'data/ptb-val.pickle'
  test_file: 'data/ptb-test.pickle'
  vocab_type: 'max_size'
  vocab_size: 10000
  min_freq: 2



model:
  model_name: 'SCPCFG'
  NT: 512
  T: 1024
  s_dim: 512
  w_dim: 512
  h_dim: 512
  z_dim: 64
  r_dim: -1
  operation_space: normal  # log -> logsumexp, normal -> muliplication  placeholder
  entropy: False # placeholder


train:
  batch_size: 16
  max_epoch: 30
  max_len: 40
  #whether to use curriculum learning stragegy.
  curriculum: 1
  start_len: 30
  increment: 1
  patience: 5
  clip: 3

test:
  batch_size: 16
  max_tokens: 100
  bucket: 32
  decode: 'mbr'
  sampler: 'batch'

optimizer:
  name: 'adam'
  lr: 0.002
  mu: 0.75
  nu: 0.999

